//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestConsoleDemo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFlowStepUserLog
    {
        public string Code { get; set; }
        public string FlowCode { get; set; }
        public string StepCode { get; set; }
        public Nullable<int> StepUserId { get; set; }
        public Nullable<int> IsApproval { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> BillId { get; set; }
        public Nullable<int> status { get; set; }
    }
}
