//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestConsoleDemo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_FlowViewInfo
    {
        public string Code { get; set; }
        public string No { get; set; }
        public string Description { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> status { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public int StepNum { get; set; }
    }
}
